<?php

/**
* @file
* A custom module for Gentle Ultimate Frisbee and how much the members have to pay.
*/

/**
* Implements hook_help.
*
* Displays help and module information.
*
* @param path
*   Which path of the site we're using to display help
* @param arg
*   Array that holds the current path as returned from arg() function
*/
function gentle_saldo_help($path, $arg) {
  switch ($path) {
    case "admin/help#gentle_saldo":
      return '<p>' . t("A custom module for Gentle Ultimate Frisbee and how much the members have to pay.") . '</p>';
      break;
  }
}

/**
* Implementation of hook_menu
*/
function gentle_saldo_menu() {
    $items['user/%user/saldo'] = array(
        'title' => t('Saldo'),
        'page callback' => 'gentle_saldo_show_saldo',
        'page arguments' => array(1),
        'access callback' => TRUE,
        'type' => MENU_LOCAL_TASK,
        );       
    return $items;
}

/**
* Show the saldo of the current user (needs improvements like using the Drupal DB API,...)
*/
function gentle_saldo_show_saldo() {
    $row = "";	
    $query = "select max(id) as id from gentle_saldo_update";
    $rs = db_query($query);

    # iterate over resultset, will be only once as we call the "max()" function
    foreach ($rs as $rs_item) {
	    $row = $rs_item;
    }

    $query = "select * from gentle_saldo_update where id = '".$row->id."'";
    $rs = db_query($query);
    
    # iterate over saldo_updates item, will be only once as the updateid is a unique primary key
    foreach ($rs as $rs_item) {
	    $row = $rs_item;
    }
    
    if (!$update_id) {
        $html = t("Er zijn nog geen saldo's beschikbaar");
        return $html;
    }

    $html = "";
    $html .= "<h2>Financieel overzicht: update van " . date("d-m-Y", $row->date) . "</h2>"; 
    $html .= "<p>Opmerking: " . $row->remarks . "</p>";

    $html .= "<table class='gentleTable'>\n\t";
	$html .= "<tr>\n\t";
	$html .= "<th align='center'>Datum</th>\n\t";
	$html .= "<th align='right'>Cumul</th>\n\t";
	$html .= "<th align='right'>Bedrag</th>\n\t";
	$html .= "<th align='left'>Beschrijving</th>\n\t";
	$html .= "<th align='left'>Opmerking</th>\n\t";
	$html .= "</tr>\n\t";

    $query = "select * from gentle_saldo_transaction where gentle_saldo_update_id = '" . $update_id . "' and uid = '" . $user->uid . "' order by datum, id";
	$rs = db_query($query);
	$cumul = 0;
    
    foreach ($rs as $row) {
		$html .= "<tr>\n\t";
		$html .= "<td align='center'>" .date("d-m-Y", $row->date) . "</td>\n\t";
		$html .= "<td align='right'>" . $cumul . "</td>\n\t";			
		$html .= "<td align='right'>" . $row->amount . "</td>\n\t";
		$html .= "<td align='left'>" . $row->description . "</td>\n\t";
		$html .= "<td align='left'>" . $row->remarks . "</td>\n";
		$html .= "</tr>\n";

		$cumul += $row->bedrag;
	}
	
	$html .= "</table>\n\t<br /><br />";
	$html .= "<strong>HUIDIG SALDO: $cumul</strong>";

    return $html;
}